spring.application.name=gestion-portefeuille

# ---------- PostgreSQL (Docker / WSL) ----------
spring.datasource.url=jdbc:postgresql://localhost:5433/portefeuille_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=portefeuille_user
spring.datasource.password=portefeuille_pwd

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

# ---------- Serveur ----------
server.port=9091