spring.application.name=gestion-portefeuille

# ---------- PostgreSQL (Docker / WSL) ----------
spring.datasource.url=jdbc:postgresql://localhost:5433/portefeuille_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=portefeuille_user
spring.datasource.password=portefeuille_pwd

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ---------- Initialisation SQL (schema.sql + data.sql) ----------
spring.sql.init.mode=always

# ---------- JWT ----------
jwt.secret=ma-cle-secrete-tres-longue-pour-signer-les-tokens-jwt-iibs-2026
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

# ---------- Serveur ----------
server.port=9091