DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS portefeuilles CASCADE;
DROP TABLE IF EXISTS utilisateurs CASCADE;

CREATE TABLE utilisateurs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(120) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    mot_de_passe  VARCHAR(255) NOT NULL,
    role          VARCHAR(10)  NOT NULL,
    date_creation TIMESTAMP    NOT NULL
);
CREATE TABLE portefeuilles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT        NOT NULL,
    solde          NUMERIC(19,2) NOT NULL,
    devise         VARCHAR(3)    NOT NULL,
    date_creation  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_portefeuille_utilisateur
        FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id),
    CONSTRAINT uk_portefeuille_utilisateur_devise
        UNIQUE (utilisateur_id, devise)
);

CREATE TABLE transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portefeuille_id  BIGINT        NOT NULL,
    type             VARCHAR(20)   NOT NULL,
    montant          NUMERIC(19,2) NOT NULL,
    date_transaction TIMESTAMP     NOT NULL,
    statut           VARCHAR(10)   NOT NULL,
    CONSTRAINT fk_transaction_portefeuille
        FOREIGN KEY (portefeuille_id) REFERENCES portefeuilles (id)
);


DROP TABLE IF EXISTS audit_logs CASCADE;

CREATE TABLE audit_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_email  VARCHAR(150) NOT NULL,
    action             VARCHAR(100) NOT NULL,
    details            VARCHAR(500),
    horodatage         TIMESTAMP    NOT NULL
);
CREATE INDEX idx_transaction_portefeuille ON transactions (portefeuille_id);
CREATE INDEX idx_transaction_date         ON transactions (date_transaction);